
name: Build and Check DicePlot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['release'] # decided to just test on latest version as sf has some dependency issues in 4.1.1 and is only used in dice_sf which is not main scope of the package

    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install system deps for sf
        run: |
          brew update
          brew install gdal geos proj udunits

      - name: Install R package dependencies
        working-directory: DicePlot
        run: |
          install.packages(c("remotes", "rcmdcheck", "sf"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        working-directory: DicePlot
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
